import{a as h,S as b,i as d}from"./assets/vendor-ee72e1a4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const L=async(e,s,o)=>{try{return await h.get("https://pixabay.com/api/",{params:{key:"44302589-5a2329cbe5164dd3461a63194",q:e,page:s,per_page:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})}catch(a){gallery.innerHTML="Something went wrong. <br/>Error happend during request.",console.error(a)}},k=(e,s)=>{s.insertAdjacentHTML("beforeend",E(e)),m.refresh()},m=new b(".gallery-link",{captionsData:"alt",captionDelay:250});m.on("error.simplelightbox",function(e){console.log(e)});function E(e){return e.reduce((s,{webformatURL:o,largeImageURL:a,tags:t,likes:r,views:i,comments:f,downloads:y})=>s+=`<li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img
          class="gallery-image"
          src="${a}" 
          alt="${t}"
        />
        <div class="picture-describe">
        <span><span class="title">Likes</span>${r}</span>
        <span><span class="title">Views</span>${i}</span>
        <span><span class="title">Comments</span>${f}</span>
        <span><span class="title">Downloads</span>${y}</span>
        </div>
      </a>
    </li>`,"")}function q(e){e.firstElementChild.checked=JSON.parse(localStorage.getItem("black"))??!1,e.firstElementChild.checked&&s(),e.addEventListener("click",o=>{e.firstElementChild.checked=!e.firstElementChild.checked,localStorage.setItem("black",JSON.stringify(e.firstElementChild.checked)),s()});function s(){document.body.classList.toggle("black"),document.body.firstElementChild.classList.toggle("black"),document.getElementById("searchrequest").classList.toggle("black")}setTimeout(()=>{e.style.opacity="0.1"},5e3)}const v="/js-study/assets/err-40fa32d5.svg",c=document.querySelector(".gallery"),n=document.getElementById("loadMore");let p,l;const u=15;n.addEventListener("click",e=>{l++,g(),setTimeout(()=>{const s=document.querySelector("li.gallery-item");window.scrollBy(0,2*s.getBoundingClientRect().height)},1e3)});document.querySelector("form").addEventListener("submit",e=>{e.preventDefault(),l=1,p=e.target.searchrequest.value,c.innerHTML="",g(),e.target.reset()});async function g(){n.textContent="",n.classList.remove("blue-btn"),n.classList.add("loader"),await L(p,l,u).then(({data:e})=>{if(e.hits.length===0){d.error(C);return}else k(e.hits,c);e.totalHits>l*u?(n.classList.add("blue-btn"),n.textContent="Load more"):(n.classList.remove("blue-btn"),l>1&&d.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}).catch(e=>{c.innerHTML="Something went wrong. <br/>Please, check your connection and try again.",console.error(e),n.classList.add("blue-btn"),n.innerHTML='<a href="/">Refreash page</a>'}),n.classList.remove("loader")}const C={position:"topRight",theme:"dark",iconUrl:v,color:"#ef4040",message:"Sorry, there are no images matching <br/>your search query. Please try again!"};q(document.querySelector(".slide"));
//# sourceMappingURL=commonHelpers.js.map
